* Посібник з кадіння під час богослужінь.
** КАДІННЯ НА "ГОСПОДИ ВЗИВАЮ"
Диякон, на горному місці, з правої сторони престолу, взявши кадило у паламаря і перехрестившись до горного місця, вкладуючи ладан у кадильницю, бере благословення у священика:
"Благослови, владико, кадило"
І здійснює кадіння:
 - святий престіл з чотирьох сторін,
 - горне Місце,
 - ікони з правої сторони вівтаря,
 - ікони з лівої сторони вівтаря,
 - запрестольний Хрест і надвратну ікону,
 - з правої сторони престолу, священика,
 - всіх людей у вівтарі.
І вийшовши північними ДИЯКОНСЬКИМИ дверми на солію, кадить:
 - надвратну ікону.
 - ікону Спасителя і праву сторону іконостасу,
 - ікону Богородиці і ліву сторону іконостасу,
 - зліва направо всіх людей в церкві,
 - зліва направо ікони і людей по всій церкві,
 - ікону на аналої посередині церкви.
На солії кадить:
 - надвратну ікону,
 - ікону Спасителя,
 - ікону Богородиці
Зайшовши у вівтар південними дияконськими дверима, кадить:
  - лице престола,
  - горне місце,
  - священика.
І віддавши кадило паламареві, разом з ним хреститься до горного місця, кланяються священикові і один одному•

** КАДІННЯ НА ПОЧАТКУ ВСЕНОШНОЇ
Священик, вложивши ладан у кадильницю і благословивши кадило, разом з дияконом, кадить:
 - Святий Престіл з чотирьох сторін
 - ікони з правої сторони вівтаря,
 - ікони з лівої сторони вівтаря,
 - запрестольний Хрест і надвратну ікону.
Священик стає перед лицем Престола. Диякон, вийшовши на солію, виголошує: *"Встаньте!"*
Диякон повертається на горне місце. Священик, роблячи кадилом знак Хреста перед святим престолом, виголошує:
*"Слава Святій..."*
Священик і диякон співають: *"Прийдіть поклонімся..."*
І після цього, священик і диякон з свічкою, виходячи царськими вратами, здійснюють кадіння всієї церкви:
- праву і ліву сторони царських врат
На солії кадять:
 - надвратну ікону,
 - ікону Спасителя і праву сторону іконостасу,
 - ікону Богородиці і ліву сторону іконостасу,
 - зліва направо всіх людей в церкві,
 - зліва направо ікони людей по всій церкві,
 - ікону на аналої посередині церкви;
На солії кадять /МК: після повернення на солію?/:
 - надвратну ікону,
 - ікону Спасителя,
 - ікону Богородиці.
Зайшовши у вівтар Царськими вратами священик кадить:
- лице престола,
- диякона
Диякон взявши кадило у священика, кадить:
 - священика.
І віддавши кадило паламареві, разом з ним хрестяться до горного місця, кланяються священикові і один одному.

** Кадіння на Літії
Диякон, на горному місці, взявши кадило у паламаря і перехрестившись до горного місця з правої сторони престолу, вкладуючи ладан у кадильницю, бере благословення у священика:
*"Благослови владико кадило"* і разом з священиком, перехрестившись два рази цілують престіл, /диякон стоїть з правої сторони престолу/ хрестяться третій раз і через горне місце+ до якого хрестяться і кланяються, виходять північними дияконськими дверми, священик в притвор, диякон на солію, де і здійснює кадіння:
 - надвратну ікону,
 - ікону Спасителя і праву сторону іконостасу,
 - ікону Богородиці і ліву сторону іконостасу,
 - ікону на аналої посередині церкви,
 - священика.
Повертається на солію і кадить:
 - людей зліва направо,
 - надвратну ікону,
 - ікону Спасителя,
 - ікону Богородиці,
 - ікону на аналої посередині церкви
 - священика.
І віддавши кадило паламареві, разом з ним хрестяться, до вівтаря, кланяються священикові і один одному.
+ Є практика виходу духовенства на літію у притвор через царські врата

** КАДІННЯ НА БЛАГОСЛОВЕННЯ ХЛІБІВ
Диякон, під час співу тропарів, кадить:
 - кругом столик, на якому знаходяться хліби, три рази,
 - священика,
 - ще один раз хліби, тільки спереду.
І віддавши кадило паламареві, разом з ним хреститься до вівтаря, кланяються священикові і один одному.

** КАДІННЯ НА ПОЛІЄЛЕЇ
Священик і диякон з свічкою, Під час співу воскресних тропарів, знаходяться посередині церкви перед аналоєм і здійснюють кадіння:
 - аналой, ця якому знаходиться ікона, з чотирьох сторін 
І заходять царськими вратами у вівтар, кадять:
 - престіл з чотирьох сторін,
 - горне місце.
 - ікони з правої сторони вівтаря.
 - ікони з лівої сторони вівтаря.
 - запрестольний	Хрест	і	надвратну ікону,
 - людей у вівтарі,
 - праву і ліву сторону царських врат.
І вийшовши на солію царськими вратами, кадять:
 - надвратну ікону,
 - ікону Спасителя і праву сторону іконостасу,
 - ікону Богородиці і ліву сторону іконостасу,
 - зліва направо всіх людей в церкві,
 - зліва направо ікони і людей по всій церкві.
На солії кадить:
 - надвратну ікону,
 - ікону Спасителя,
 - ікону Богородиці,
 - ікону на аналої посередині церкви,
 - диякона.
Диякон, взявши кадило у священика кадить:
 - священика.
І віддавши кадило паламареві, разом з ним хрестяться до вівтаря, кланяються священикові і один одному.

** КАДІННЯ НА 9-Й ПІСНІ КАНОНУ
Диякон, на горному місці, з правої сторони Престолу, взявши кадило у паламаря і перехрестившись до горного місця, вкладаючи ладан у кадильницю, бере благословення у священника:
*"Благослови, владико, кадило"*
і здійснює кадіння:
 - святий Престіл з чотирьох сторін,
 - горне місце,
 - ікони з правої сторони вівтаря,
 - ікони з лівої сторони вівтаря,
 - запрестольний Хрест і надвратну ікону,
 - всіх людей у вівтарі.
І вийшовши північними дияконськими дверми на солію, кадить:
 - надвратну ікону,
 - ікону Спасителя і праву сторону іконостасу;
Ставши перед намісною іконою Богородиці і дочекавшись закінчення співу катавасії після 8-ї пісні, виголошує:
*"Богородицю..."*
І продовжує кадіння:
 - ікону Богородиці і ліву сторону іконостасу+,
 - зліва направо всіх людей в церкві,
 - зліва направо ікони і людей по всій церкві,
 - ікону на аналої посередині церкви++
На солії кадить:
 - надвратну ікону,
 - ікону Спасителя.
 - ікону Богородиці
Зайшовши у вівтар південними дияконськими дверми кадить:
 -лице престола.
 - горне місце.
 - священика.
І віддавши кадило паламареві, разом з ним хрестяться до горного місця, кланяються священикові і один одному.
+ Якщо священик продовжує здійснювати єлеопомазання, диякон іде до аналою посередині церкви, кадить ікону на аналої і священика і повертається на солію, де і продовжує кадіння людей.
++ Якщо священик продовжує здійснювати єлеєпомазання диякон кадить священика і повертається на солію.

** ﻿Кадіння на часах /Перед початком Літургії/
Диякон, після відпусту проскомидії, відкриває завісу царських врат, іде на горне місце, бере кадило у паламаря і перехрестившись до горного місця, вкладаючи ладан у кадильницю, бере благословення у священика:
*"Благослови владико кадило"*
І кадить:
 - престіл з чотирьох сторін, з словами: "В гробі" і 50 пс.
 - жертовник,
 - горне місце.
 - ікони з правої сторони вівтаря,
 - ікони з лівої сторони вівтаря,
 - запрестольний Хрест і надвратну ікону,
 - священика,
 - всіх людей у вівтарі.
І вийшовши Північними дияконськими дверми, на солію, кадить:
 - надвратну ікону,
 - ікону Спасителя і праву сторону іконостасу,
 - ікону Богородиці і ліву сторону іконостасу,
 - зліва направо людей в церкві+,
 - надвратну ікону,
 - ікону Спасителя,
 - ікону Богородиці,
І зайшовши південними дияконськими дверми у вівтар, кадить:
 - лице престола,
 - горне місце,
 - священика.
І віддавши кадило паламареві, разом з ним хреститься до горного місця, кланяються священикові і один одному.
+ Є практика здійснювати кадіння всієї церкви.

** КАДІННЯ ПІД ЧАС ЧИТАННЯ АПОСТОЛА
Диякон, під час закінчення співу Трисвятого, на горному місці, бере кадило у паламаря і перехрестившись до горного місця, підносить кадило до священика і просить благословення.
Священик, вкладуючи ладан у кадильницю, благословляє кадило.
Диякон, лід час прокімна кадить:+
 - престіл з чотирьох сторін, читаючи 50 пс.,
 - жертовник,
 - горне місце,
 - ікони з правої сторони вівтаря,
 - ікони з лівої сторони вівтаря, .
 - запрестольний Хрест і надвратну ікону.
Під час читання Апостола, кадить:
 - праву і ліву сторону царських врат.
Вийшовши царськими вратами на солію, кадить:
 - надвратну ікону,
 - ікону Спасителя і праву сторону іконостасу,
 - ікону Богородиці і ліву сторону іконостасу.
Повернувшись у вівтар царськими вратами, кадить:
 - священика,
 - людей у, вівтарі
Вийшовши царськими вратами на солію, кадить:
 - читаючого Апостола,
 - зліва направо всіх людей у церкві,
 - надвратну ікону,
 - ікону Спасителя,
 - ікону Богородиці.
Повернувшись у вівтар царськими вратами, кадить:
 - лице престола,
 - священика,
і віддавай кадило паламареві, разом з ним хрестяться до горного місця, кланяються священикові і один одному.

** КАДІННЯ ПІД ЧАС СПІВУ ХЕРУВИМСЬКОЇ ПІСНІ
Диякон, під час співу Херувимської пісні, на горному місці, бере кадило у паламаря і перехрестившись до горного місця, вкладуючи ладан у кадильницю бере благословення у священика:
*"Благослови, владико, кадило"*
І кадить:
 - престіл з чотирьох сторін, читаючи 50 пс.,
 - жертовник,
 - горне місце.
 - ікони з правої сторони вівтаря.
 - ікони з лівої сторони вівтаря, 
 - запрестольний Хрест і надвратну ікону,
 - праву і ліву сторону царських врат.
І вийшовши царськими вратами на солію, кадить:
 - надвратну ікону,
 - ікону Спасителя і праву сторону іконостасу,
 - ікону Богородиці і ліву сторону іконостасу;
Повернувшись у вівтар царськими вратами, кадить:
 - священика,
 - людей у вівтарі.
Вийшовши царськими вратами на солію, кадить:
 - зліва направо всіх людей у церкві,
 - надвратну ікону,
 - ікону Спасителя,
 - ікону Богородиці.
Повернувшись у вівтар царськими вратами, кадить:
 - лице престола,
 - священика.
І віддавши кадило паламареві разом з ним хрестяться до горного місця, кланяються священикові і один одному.

** КАДІННЯ ПІД ЧАС СПІВУ "ДОСТОЙНО Є"
Священик, взявши кадило у диякона, і покадивши три рази по три лице престола виголошує:
*"Особливо..."*
І віддає кадило диякону, який кадить:
 - престіл з трьох сторін,
 - горне місце,
 - ікони з правої сторони вівтаря,
 - ікони з лівої сторони вівтаря,
 - запрестольний Хрест і надвратну ікону,
 - священика, з правої сторони престолу,
 - всіх людей у вівтарі,
 - лице престола,
 - горне місце,
 - священика.
І віддавши кадило паламареві, разом з ним хрестяться до горного місця, кланяються священикові і один одному.

** КАДІННЯ НА ПАРАСТАСІ
На: "Благослови єси Господи..."
На: "Зо святими упокой..."
На: "Вічну пам'ять..."
Священик з кадилом, диякон з свічкою+ кадить:
 - ікону на аналої, посередині церкви, з чотирьох сторін
На солії кадить:
 - ікону нядвратну,
 - ікону Спасителя і праву сторону іконостасу,
 - ікону Богородиці і ліву сторону іконостасу,
 - зліва направо всіх людей у церкві,
 - надвратну ікону,
 - ікону Спасителя,
 - ікону Богородиці,
 - спереду ікону на аналої, посередині церкви,
 - диякона.
Диякон взявши кадило у священика, кадить:
 - священика.
І віддавши кадило паламареві, разом з ним хрестяться до вівтаря, кланяються священикові і один одному.
+ На: "Вічну пам'ять...", диякон здійснює кадіння сам.
